#!/bin/bash

# JAVA path
export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
export PATH=/usr/lib/jvm/java-17-openjdk-amd64/bin:"$PATH"

# aws access variables 
aws_access_key_id=ASIAZCEQWUFM2FLM7K46
aws_secret_access_key=f1fPttkeajSf+ZphOQ+uER4HKS+qkeNOcL7yMpBU
aws_session_token=IQoJb3JpZ2luX2VjENX//////////wEaCXVzLXdlc3QtMiJHMEUCIQCdXkP5xEMUVNhehY3V9dGFrbgBecTQlwsaGUwfTpUQSQIgQvmMaTlqVyPaXQPGCCKH13ZS6LLYX9B0BfntbVhjO5IqwwIInv//////////ARABGgw2MjMwNzM3MzA5MDUiDBO0kpLvQw37E1ddGiqXAj+MO93rnngZEEoMpf9vbe34+c4lezw62RcWNBzaBXWS+BvtRjJoDDv21gcccFzGIzRvXtisfyLYs24xaLa2jEzUpNONb3Ndp9ZtT+3IqDvJU9olGXw5qDilMFK50UwKqeOs5MhUH/2iF7bq3FvAmcSwXRH/Jes2Jwm/HDomifrlUbOpmdRlWL6gwyN6SLtdqIhMC2Wh889jlSoNbXzLLRR1LiskGH8a5YuRqY7q4r5453VnKcewNlu3XqXOi7TwvAH5wVrvrQZ5PARPDQ5NGP+9NZWyfCM7ZgLRi8EmCwKQh3dzm3ELrNsjZq6RIeq92fPBABGvKK1E/c0FuZ+WDI4FDDEJYBT0bbK74+7JrD8diGuphQBM4DDc3ZXRBjqdAa8fXqibHGqOSF9wIgaSSN0pRTYXwAooQOb3i8DPM2XAQx+s9H27ZmsflvlNkrLat1I9VjkleKm6QS5/JwRGWBm0sthnY5gmZBcDfGC7zU/ikuNZwHpLF6RwDyGsabmE/gA+bS8m09+3zL3Y+C3JZpPHrQIT+S0B4uzn5jXftA2LuzttyDAVh1IcYT/ahihaeCEyavpeCv5a3OWY5Zk=


# docker access variables
yourDockerUsername=watchyojet
yourDockerPassword=dckr_pat_Fi78bFUoqKyPyhyuibKbM5s6szU

# exporting all variables to be used by next scripts
export AWS_ACCESS_KEY_ID=$aws_access_key_id
export AWS_SECRET_ACCESS_KEY=$aws_secret_access_key
export AWS_SESSION_TOKEN=$aws_session_token
export DockerUsername=$yourDockerUsername
export DockerPassword=$yourDockerPassword


