quarkus.datasource.db-kind=mysql
quarkus.datasource.username=teste
quarkus.datasource.password=testeteste

quarkus.swagger-ui.path=swagger-ui
quarkus.swagger-ui.always-include=true

%prod.quarkus.container-image.build=true
%prod.quarkus.container-image.push=true
%prod.quarkus.container-image.docker.buildx.platform=linux/amd64,linux/arm64
%prod.quarkus.container-image.group=watchyojet
%prod.quarkus.datasource.reactive.url=mysql://placeholder:3306/VPPaaS
