quarkus.swagger-ui.path=swagger-ui
quarkus.swagger-ui.always-include=true

ollama.url=http://localhost:11434
flexibilityevent.service.url=http://ec2-32-192-249-95.compute-1.amazonaws.com:8080
quarkus.container-image.group=watchyojet
quarkus.datasource.reactive.url=mysql://ieproject202620260509140946179500000001.ctsic4aeg78g.us-east-1.rds.amazonaws.com:3306/VPPaaS
