quarkus.swagger-ui.path=swagger-ui
quarkus.swagger-ui.always-include=true

%prod.quarkus.container-image.build=true
%prod.quarkus.container-image.push=true
%prod.quarkus.container-image.docker.buildx.platform=linux/amd64,linux/arm64
%prod.quarkus.container-image.group=watchyojet
%prod.ollama.url=http://localhost:11434
%prod.flexibilityevent.service.url=http://placeholder:8080
%test.ollama.url=http://localhost:9999
%test.flexibilityevent.service.url=http://localhost:9999
