quarkus.datasource.db-kind=mysql
quarkus.datasource.username=teste
quarkus.datasource.password=testeteste

quarkus.swagger-ui.path=swagger-ui
quarkus.swagger-ui.always-include=true

quarkus.container-image.build=true
quarkus.container-image.push=true


kafka.bootstrap.servers=ec2-18-208-163-145.compute-1.amazonaws.com:9092
telemetry.service.url=http://ec2-52-90-41-227.compute-1.amazonaws.com:8080
quarkus.container-image.group=DOCKER_USERNAME
quarkus.datasource.reactive.url=mysql://ieproject202620260510170233144900000001.ctsic4aeg78g.us-east-1.rds.amazonaws.com:3306/VPPaaS
