title Asset Link Deletion Business Process

actor Prosumer
participant Camunda
participant VPPaaS
participant Kong
participant "AssetLink Service" as Service

Prosumer->Camunda: Fill deletion data\n(assetLinkID)
Camunda->VPPaaS: Request Asset Link Deletion
activate VPPaaS
VPPaaS->VPPaaS: Verify if deletion is possible\n(promise: true/false)

alt promise = true
  VPPaaS-->Camunda: Promise
  VPPaaS->Kong: DELETE /AssetLink/{id}
  Kong->Service: Forward Delete Request
  activate Service
  Service->Database: DELETE AssetLink record
  Database-->Service: OK
  Service-->Kong: Response
  deactivate Service
  Kong-->VPPaaS: Response
  VPPaaS-->Camunda: Declare
  Camunda->Prosumer: Check Deletion order\n(confirmed)
  Prosumer->Camunda: Accept
  Camunda-->VPPaaS: Accept
else promise = false
  VPPaaS-->Camunda: Decline
  Camunda->Prosumer: Decide what to do next\n(retry or abort)
end
deactivate VPPaaS
