title Asset Link Management Business Process

Camunda->Kong: CRUD Request (GET / DELETE)
Kong->AssetLink Service: Forward CRUD Request
activate AssetLink Service
AssetLink Service->Database: Read/Write AssetLink data
Database-->AssetLink Service: Result
AssetLink Service-->Kong: Response
deactivate AssetLink Service
Kong-->Camunda: Forward Response


note over Camunda: Triggered when creating a new AssetLink

Camunda->Kong: Create Asset Link
Kong->AssetLink Service: Forward Create Request
activate AssetLink Service
AssetLink Service->Database: INSERT AssetLink\n(idProsumer, idUtilityOperator)
Database-->AssetLink Service: OK (returns new AssetLink ID)
AssetLink Service->Kafka: Create Topic\n(AssetLinkID-UtilityOperatorName)\ne.g. "1-EDP"
note right of Kafka: Topic name format:\nAssetLinkID-UtilityOperatorName
Kafka-->AssetLink Service: Topic created
AssetLink Service->Telemetry Service: Register Topic for Consumption
activate Telemetry Service
Telemetry Service->Kafka: Subscribe to new topic
note right of Telemetry Service: Spawns DynamicTopicConsumer thread
Kafka-->Telemetry Service: Subscribed
Telemetry Service-->AssetLink Service: OK
deactivate Telemetry Service
AssetLink Service-->Kong: Response
deactivate AssetLink Service
Kong-->Camunda: Forward Response
